name: Coverity Scan
on:
  schedule:
    - cron: '0 4 * * 1'  ## every Monday morning
env:
  COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
  COVERITY_SCAN_EMAIL: github@stefanlau.com
  COVERITY_PROJECT: ja2-stracciatella/ja2-stracciatella
  COV_BUILD_DIR: coverage-build
  COV_BUILD_RESULTS_FILE: analysis-results.tgz

jobs:
  coverity_scan:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        shell: bash
        run: ${{ github.workspace }}/.ci/ci-setup.sh 2>&1
        env:
          CI_TARGET: linux

      - name: Download and install Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 \
                --post-data "token=${COVERITY_SCAN_TOKEN}&project=${COVERITY_PROJECT}" \
                -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
          export PATH=$(pwd)/cov-analysis-linux64/bin:$PATH

      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share

      - name: Prepare CMake build
        run: |
          mkdir ${COV_BUILD_DIR} && pushd ${COV_BUILD_DIR}
          cmake ${CMAKE_BUILD_OPTIONS} ..
        env:
          CMAKE_BUILD_OPTIONS: "-DCMAKE_BUILD_TYPE=Release"

      - name: Run Coverity Scan Analysis Tool
        run: |
          cov-build --dir ${COV_BUILD_DIR} make
          cov-import-scm --dir ${COV_BUILD_DIR} --scm git --log ${COV_BUILD_DIR}/scm_log.txt

      - name: Upload Coverity Scan Analysis results
        run: |
          tar czf ${COV_BUILD_RESULTS_FILE} ${COV_BUILD_DIR}
          curl \
            --form project=${COVERITY_PROJECT} \
            --form token=${COVERITY_SCAN_TOKEN} \
            --form email=${COVERITY_SCAN_EMAIL} \
            --form file=@${COV_BUILD_RESULTS_FILE} \
            --form version={{ github.sha }} \
            --form description="GitHub nightly" \
              https://scan.coverity.com/builds?project=${COVERITY_PROJECT}

      - name: Upload scan logs as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: scan-logs
          path: |
            ${{ env.COV_BUILD_DIR }}/cov-int/build-log.txt
            ${{ env.COV_BUILD_DIR }}/cov-int/scm_log.txt